import * as Basic from './Basic'
import * as Mol from './Mol'
import * as Flow from './Flow'
import * as Spring from './Spring'
import * as Trail from './Trail'
import * as Cannon from './Cannon'
// import * as Hel from './Hel'
// import * as Plant from './Plant'
// import * as Swarm from './Swarm'
export default {Basic, Flow, Mol, Spring, Trail, Cannon}
